# Generated by Django 2.2.6 on 2019-11-21 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_employer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Province'),
        ),
    ]
