# Generated by Django 2.2.6 on 2019-11-22 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20191122_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerprofile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='employerprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='profile_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='profile_ptr',
            field=models.OneToOneField(auto_created=True, default=6, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.Profile'),
            preserve_default=False,
        ),
    ]
