# Generated by Django 2.2.6 on 2019-11-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20191122_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
    ]
