# Generated by Django 2.2.6 on 2019-11-23 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20191123_1740'),
        ('users', '0009_auto_20191123_0214'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
