# Generated by Django 2.2.6 on 2019-11-26 14:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20191125_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='expire_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 19, 14, 35, 32, 108817, tzinfo=utc), verbose_name='Job Expiration Date'),
        ),
    ]
